README.md
package.json
scripts/copyBuildFiles.js

Update package.json with details for public NPM package.
Update build script with new package name.
Update readme to reflect changes to package.

Updates to project setup

---

src/components/TextareaInput/TextareaInput.js

one final piece of design feedback

add padding

---

CONTRIBUTING.md
package.json
scripts/cleanPackageJson.js

* Adds merge guidelines and other info to contributing docs.
* Change node engine to >8.
* Remove unused name variable from clean package script.

docs(contributing): Update contributing docs

---

src/components/TextareaInput/TextareaInput.js
src/components/TextareaInput/TextareaInput.spec.js

fix(TextAreaInput):Fixing click behavior of input - issue #22

---

src/components/StepChain/StepChain.js
src/components/StepChain/StepChain.stories.js
src/components/StepChain/index.js

Another piece to the VM UI update. I thought it might be useful here too. It takes a list of steps and a number for current step.

added StepChain

---

src/components/AccordionList/AccordionList.stories.js
src/components/InteractiveElement/InteractiveElement.js
src/components/InteractiveElement/InteractiveElement.stories.js
src/components/InteractiveElement/index.js
src/components/OverflowMenu/OverflowMenu.js
src/components/OverflowMenu/OverflowMenu.stories.js
src/components/OverflowMenu/index.js
src/components/icons/index.js
src/components/index.js

Adding the InteractiveElement and OverflowMenu components from the client app.

Porting Over Components

---

src/components/SelectInput/SelectInput.js
src/components/SelectInput/SelectInput.stories.js
src/components/SelectInput/SelectInputDisplay.js
src/components/SelectInput/SelectOptions.js
src/components/TextInput/TextInput.js
src/components/TextInput/TextInput.stories.js

* Modify the TextInput component to add a search input option.
* Add a searchable list option and button display option to the SelectList component.

Add search field and button display option to SelectList component.

---

src/components/SelectInput/SelectInput.js
src/components/SelectInput/SelectOptions.js
src/components/TextInput/TextInput.js

Reverts InsideSalesOfficial/insidesales-components#45

Revert "Fix searchable options"

---

src/components/SelectInput/SelectInput.js
src/components/SelectInput/SelectOptions.js
src/components/TextInput/TextInput.js

This reverts commit b51950b15a25c90f7b1bc5d4650cb6556748627a.

fix(SelectInput): Fixed search option and clearing out filter text on close.

---

src/components/RadioList/Radio.js

Fixed minor css issue by adding "box-sizing: content-box" to radio circle so global styles will no longer make it a border-box.

fix(RadioStyle): Fixed minor css issue

---

src/components/SelectInput/SelectOptions.js

Fixed bug with searchable select options

fix(SelectOptions): fixed issue with text being reset

---

src/components/Button/Button.js
src/components/ButtonBar/ButtonBar.js
src/components/ButtonBar/ButtonBar.stories.js
src/components/ButtonBar/index.js
src/components/Loader/Loader.js
src/components/Loader/Loader.stories.js
src/components/Loader/index.js
src/components/MessageDialog/MessageDialog.js
src/components/MessageDialog/MessageDialog.stories.js
src/components/MessageDialog/index.js
src/components/index.js

* Add MessageDialog Component
* Update Button Component
* Add ButtonBar Component

feat(MessageDialog): Add MessageDialog, ButtonBar, and update Button

---

src/components/TextInput/TextInput.js

fix(TextInput): Adding line color to textbox.

fix(TextInput): Adding line color to textbox.

---

src/components/SelectInputLabelBox/SelectInputLabelBox.js
src/components/TextInput/TextInput.js
src/components/TextareaBox/TextareaBox.js
src/components/TextareaBox/TextareaBox.stories.js
src/components/TextareaBox/index.js
src/components/index.js

Added resizing textarea box reusing styles and code from Textinput
Empty, Unfocused
Focused
Unfocused with text: 
Error

feat(TextareaBox): Added resizing textarea box

---

src/components/SelectInputLabelBox/SelectInputLabelBox.js

Added function to determine which option label should be displayed

fix(SelectInputLabelBoxLabel): Added function to determine which option label should be displayed

---

src/components/index.js

Export colors, boxShadows, scrollbars, and typography so that they can be used externally

feat(Styles): Export styled to be used externally

---

src/components/SelectInput/SelectInput.js
src/components/SelectInput/SelectInput.stories.js

Allow selectOptionsWidth prop in SelectInput component, similar to the existing TextInput prop

fix(SelectInput): selectOptionsWidth prop on SelectInput component

---

src/components/TextInput/TextInput.js
src/components/TextInput/TextInput.stories.js

added placeholder attribute to TextInput
fixed some problems on the story

feat(TextInput): added placeholder attribute

---

src/components/styles/colors.stories.js
src/components/styles/typography.stories.js

feat(colors, typography): Added stories for colors and typography

---

.travis.yml
src/components/ActionButton/ActionButton.js
src/components/ActionOverflowButtons/ActionOverflowButtons.js
src/components/icons/AddIcon.js
src/components/icons/EditFilledIcon.js

Add title attr to action button;
remove some icon titles
Also, I made a small change to the travis file to see if it will fix automation issues.

fix(ActionButton): add title support

---

src/components/DropdownButton/DropdownButton.js
src/components/DropdownButton/DropdownButton.stories.js

Errant `console.log` was left in the code. Also, there was a bug where the value for options had to be it's index in the options array. Now the value can be anything (including a string).

 bug(DropdownButton): Remove `console.log` and fix value issue

---

src/components/TextareaInput/TextareaInput.js
src/components/TextareaInput/TextareaInput.spec.js
src/components/TextareaInput/TextareaInput.stories.js

* allows char limit
* shows char count if char limit is present
* creates error message if char count goes over char limit
* adjusts the layout of the error message to account for the char count if the char limit is present

feat(textarea input char count)

---

src/components/TextareaInput/TextareaInput.js

* fixed a few things that didn't make it in due to some git confusion

fix(TextareaInput error): fix for errors not appearing

---

src/components/TextareaInput/TextareaInput.js
src/components/TextareaInput/TextareaInput.spec.js
src/components/TextareaInput/TextareaInput.stories.js

fix(TexareaInput placeholder): add placeholder property

---

src/components/FilterBar/FilterBar.js
src/components/FilterBar/FilterBar.stories.js
src/components/FilterBar/index.js
src/components/SelectInput/SelectInput.js
src/components/SelectInput/SelectInput.stories.js
src/components/SelectInput/SelectInputDisplay.js
src/components/SelectInput/SelectInputLabel.js
src/components/icons/FilterIcon.js
src/components/icons/index.js

feat(FilterBar): Added FilterBar component

---

src/components/ActionOverflowButtons/ActionOverflowButtons.js
src/components/FilterBar/FilterBar.js
src/components/FilterBar/FilterBar.stories.js

* Allow hiding the filter button on the filter bar
* Fix actionoverflowbutton animation when opening up

fix(FilterBar): Allow hiding filter button

---

src/components/FilterBar/FilterBar.js
src/components/FilterBar/FilterBar.stories.js

fix(FilterBar): Add promotedSortOptions prop

---

src/components/Checkbox/Checkbox.js
src/components/SelectInputLabelBox/SelectInputLabelBox.stories.js

When a checkbox is clicked it shows as clicked instead of having to wait until something else is clicked.

fix(SelectInputLabelBox): multiselect checkboxes work as expected

---

src/components/icons/MergeFieldIcon.js

fix(MergeIcon): changing invalid react attribute

---

src/components/icons/VideoLibraryIcon.js
src/components/icons/index.js

feat(Icons): Adding video library icon

---

src/components/icons/ArrowForward.js
src/components/icons/CallForward.js
src/components/icons/Notes.js
src/components/icons/index.js

Add missing icons for the new nav bar

feat(Icons): Add Icons for new nav bar

---

CODEOWNERS

Add codeowners file so we can have required reviewers

feat(CODEOWNERS): Add codeowners file

---

src/components/OverflowMenuButton/OverflowMenuButton.js
src/components/OverflowMenuButton/OverflowMenuButton.stories.js
src/components/OverflowMenuButton/OverflowMenuButtonThemes.js
src/components/OverflowMenuButton/index.js
src/components/styles/colors.js

Designer added two sets of disabled color on dark background for normal email send and neural send.

feat(overflowMenuButton): add overflowMenuButton

---

package-lock.json
src/components/ButtonBar/ButtonBar.js
src/components/MessageDialog/MessageDialog.stories.js

feat(MessageDialog): Add prop for adding 'danger' to the primary button

---

src/components/icons/HelpCircleIcon.js
src/components/icons/MobilePhoneIcon.js
src/components/icons/PrintIcon.js
src/components/icons/RemoveCircleIcon.js
src/components/icons/VerifyFilledIcon.js
src/components/icons/VerifyIcon.js
src/components/icons/index.js

VerifyFilledIcon
VerifyShieldIcon renamed to VerifyIcon
MobilePhoneIcon
PrintIcon
RemoveCircleIcon
HelpCircleIcon

feat(Verify State Icons): new neural verify state icons

---

src/components/icons/PauseOutlined.js
src/components/icons/PlayOutlined.js
src/components/icons/Record.js

Adding the Record, PlayOutlined, and PauseOutlined icons

feat(Icons): adding record icons

---

src/components/TextInput/TextInput.js

Added `autoFocus` prop to TextInput, which will append `autofocus` attribute to input element.

feat(TextInput): added `autoFocus` prop to TextInput

---

src/components/icons/index.js

feat(Icons): fix recording icons

---

src/components/SelectInput/SelectInput.js
src/components/SelectInput/SelectInput.stories.js

Add searchText prop to options where option.label is a react component instead of a string for easier filtering.

fix(SelectInput): Add optional searchText prop to options

---

src/components/SearchBox/SearchBox.js
src/components/SnippetButton/SnippetButton.js

This works better than just giving the SearchBox component an ID.

fix(SearchBox): Add ID properties for Cypress

---

src/themeHelpers/sassConfiguration.js

Spread colors into Color constructor in sassConfiguration

fix(SassThemes): Spread colors into Color constructor in sassConfiguration

---

src/components/FilterBar/FilterBar.js
src/components/FilterBar/FilterBar.stories.js
src/components/SelectInput/SelectInputDisplay.js

Theme Filter Bar
Consume passed theme background in select input display (to fix transparency)

feat(Theming): Theme filter bar

---

src/components/DatePicker/DatePicker.js
src/components/DatePicker/DatePicker.stories.js
src/components/DatePicker/example.js

Updated date picker with new colors

feat(DatePicker): Themeing

---

src/components/DatePicker/DatePicker.stories.js
src/components/TextInput/TextInput.js
src/components/TextInput/TextInput.stories.js
src/components/TextInputBox/TextInputBox.js
src/components/TextInputBox/TextInputBox.stories.js

Added new theme to TextInput and TextInputBox

feat(TextInput): new theme

---

src/components/DatePicker/DatePicker.js

Makes it so the color shows up again, and fixes the height changing on focus.

fix(DatePicker): bottom border style

---

src/components/StepChain/StepChain.js

I failed to include unique keys when making the new step-chain. This fixes that.

fix(Chain): Add keys to stepchain array

---

src/components/icons/StarUnFilledIcon.js
src/components/icons/index.js

Added New Star Icon SVG (unfilled)

feat(StarUnFilledIcon): added icon star unfilled

---

src/components/Thumbnail/Thumbnail.js

Before: <img width="356" alt="Screen Shot 2020-02-13 at 12 08 42 PM" src="https://user-images.githubusercontent.com/1188980/74475240-46381c80-4e64-11ea-8477-d30b9f7734d2.png">
After: <img width="362" alt="Screen Shot 2020-02-13 at 12 12 21 PM" src="https://user-images.githubusercontent.com/1188980/74475239-459f8600-4e64-11ea-83cf-d0021ba3d9b6.png">

fix(Thumbnail): Change arrow color to match bg

---

package.json

fix(SemanticRelease): tick semantic release version

fix(SemanticRelease): tick semantic release version

---

src/components/Modal/Modal.js
src/components/NeuralVerifyShield/index.js
src/components/SelectInput/SelectOptions.js

modal and select input styling changes/overrides

feat(Mobile): Feat scrollable modal and no hover verify

---

src/components/SortableList/SortableList.js

dont store state when you dont need to.

feat(SortableList): make sortable list a dumb view

---

src/components/DatePicker/DatePicker.js

feat(DatePicker): Adding ability to have an empty date initially

---

src/components/SelectInput/SelectOptions.js

fix(SelectOption): try passed key first

---

src/components/PairedButtons/PairedButtons.js
src/components/SelectInput/SelectInput.js
src/components/SelectInput/SelectInput.stories.js
src/components/icons/CloseCircleIcon.js

Fixing select input classes, ids, and icon

fix(SelectInput): Fix select input classes, ids, and icons

---

src/components/SelectInput/SelectOptions.js

PB-2774 Added title attribute to SelectOptions (used for SelectInput and SelectInputLabelBox).

feat(SelectInput): Add title attribute for hover
